
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/venv/bin/"
      - "/vscode/cursor-server/bin/linux-x64/20adc1003928b0f1b99305dbaf845656ff81f5d0/bin/remote-cli/"
      - "/usr/local/cargo/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
    searched_directories:
      - "/opt/venv/bin/uname"
      - "/vscode/cursor-server/bin/linux-x64/20adc1003928b0f1b99305dbaf845656ff81f5d0/bin/remote-cli/uname"
      - "/usr/local/cargo/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/opt/venv/bin"
        - "/vscode/cursor-server/bin/linux-x64/20adc1003928b0f1b99305dbaf845656ff81f5d0/bin/remote-cli"
        - "/opt/venv/bin"
        - "/opt/venv/bin"
        - "/usr/local/cargo/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-161-generic - x86_64
...
